# Import libraries, set config

In [4]:
import sys
import os

sys.path.append(os.path.abspath(".."))

import pandas as pd              # data manipulation
import numpy as np               # numerical computing
import matplotlib.pyplot as plt  # visualization
import shap                      # model interpretability
import mlflow                    # experiment tracking

from src.data_loader import load_and_validate_data

RANDOM_SEED = 42
np.random.seed(RANDOM_SEED)

In [11]:
# Core files (required)
core_files = {
    "ratings": "../data/raw/user_ratedmovies.dat",
    "movies": "../data/raw/movies.dat",
    "movies_genres": "../data/raw/movie_genres.dat"
}

core_data = {name: load_and_validate_data(path, sep='\t', encoding="latin-1") 
             for name, path in core_files.items()}

# Optional content features
content_files = {
    "movie_actors": "../data/raw/movie_actors.dat",
    "movie_directors": "../data/raw/movie_directors.dat",
    "movie_countries": "../data/raw/movie_countries.dat",
    "movie_locations": "../data/raw/movie_locations.dat",
    "movie_tags": "../data/raw/movie_tags.dat"
}

content_data = {name: load_and_validate_data(path, sep='\t', encoding="latin-1")
                for name, path in content_files.items()}

# Tags
tag_files = {
    "tags": "../data/raw/tags.dat",
    "user_taggedmovies": "../data/raw/user_taggedmovies.dat"
}

tags_data = {name: load_and_validate_data(path, sep='\t', encoding="latin-1")
             for name, path in tag_files.items()}

data = {**core_data, **content_data, **tags_data}

../data/raw/user_ratedmovies.dat
 Loaded 855598 rows and 9 columns
No missing values
Number of duplicate rows: 0

../data/raw/movies.dat
 Loaded 10197 rows and 21 columns
Missing values detected:
imdbPictureURL    181
rtID              311
dtype: int64
Number of duplicate rows: 0

../data/raw/movie_genres.dat
 Loaded 20809 rows and 2 columns
No missing values
Number of duplicate rows: 0

../data/raw/movie_actors.dat
 Loaded 231730 rows and 4 columns
Missing values detected:
actorName    5
dtype: int64
Number of duplicate rows: 0

../data/raw/movie_directors.dat
 Loaded 10155 rows and 3 columns
No missing values
Number of duplicate rows: 0

../data/raw/movie_countries.dat
 Loaded 10197 rows and 2 columns
Missing values detected:
country    8
dtype: int64
Number of duplicate rows: 0

../data/raw/movie_locations.dat
 Loaded 49163 rows and 5 columns
Missing values detected:
location1     1268
location2     2629
location3     6856
location4    26555
dtype: int64
Number of duplicate rows: 0

../data/raw/movie_tags.dat
 Loaded 51795 rows and 3 columns
No missing values
Number of duplicate rows: 0

../data/raw/tags.dat
 Loaded 13222 rows and 2 columns
No missing values
Number of duplicate rows: 0

../data/raw/user_taggedmovies.dat
 Loaded 47957 rows and 9 columns
No missing values
Number of duplicate rows: 0

In [12]:
data['ratings']

,userID,movieID,rating,date_day,date_month,date_year,date_hour,date_minute,date_second
0,75,3,1.0,29,10,2006,23,17,16
1,75,32,4.5,29,10,2006,23,23,44
2,75,110,4.0,29,10,2006,23,30,8
3,75,160,2.0,29,10,2006,23,16,52
4,75,163,4.0,29,10,2006,23,29,30
...,...,...,...,...,...,...,...,...,...
855593,71534,44555,4.0,3,12,2007,3,5,38
855594,71534,46578,4.0,3,12,2007,2,56,44
855595,71534,48516,4.5,3,12,2007,2,53,46
855596,71534,61075,5.0,10,10,2008,9,56,5
855597,71534,62049,4.5,10,10,2008,9,58,10

In [13]:
data["movie_countries"]

       movieID country
0            1     USA
1            2     USA
2            3     USA
3            4     USA
4            5     USA
...        ...     ...
10192    65088     USA
10193    65091     USA
10194    65126     USA
10195    65130     USA
10196    65133      UK

[10197 rows x 2 columns]